[book]
authors = ["KS Plus e.V."]
language = "en"
multilingual = false
src = "src"
title = "K.S.C.H. Workflows Architecture"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/ksch-workflows/architecture/issues"
edit-url-template = "https://github.com/ksch-workflows/architecture/issues/new?title=[{path}]"

[output.html.fold]
enable = true
level = 0
